### ISSUE TITLE
generate not wokring: "Unable to find template plugin matching @twinlogix/typetta"

### ISSUE THREAD

**Issue by Atlinx** [twinlogix/typetta#195]
I'm following the [getting started tutorial](https://twinlogix.github.io/typetta/chapters/overview/getting-started) and I'm getting this error when I'm running `npm run generate`. I have `@twinlogix/typetta` installed, so I don't understand why I'm getting the error.

```
AggregateError: Something went wrong Unable to find template plugin matching @twinlogix/typetta for "C:\Path\To\LearnTypetta\src\generated\operations.ts"
        Unable to find template plugin matching '@twinlogix/typetta'
        Install one of the following packages:


        - @graphql-codegen/@twinlogix/typetta
        - @graphql-codegen/@twinlogix/typetta-template
        - @graphql-codegen/@twinlogix/typetta-plugin
        - graphql-codegen-@twinlogix/typetta
        - graphql-codegen-@twinlogix/typetta-template
        - graphql-codegen-@twinlogix/typetta-plugin
        - codegen-@twinlogix/typetta
        - codegen-@twinlogix/typetta-template
        - @twinlogix/typetta

    at executeCodegen (C:\Path\To\LearnTypetta\node_modules\@graphql-codegen\cli\index.js:1078:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async generate (C:\Path\To\LearnTypetta\node_modules\@graphql-codegen\cli\index.js:1388:25)
    at async Command.exports.default (C:\Path\To\LearnTypetta\node_modules\@twinlogix\typetta\lib\cli\generate\generate.js:51:21)

Error: Unable to find template plugin matching @twinlogix/typetta
    at getPluginByName (C:\Path\To\LearnTypetta\node_modules\@graphql-codegen\cli\index.js:288:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async C:\Path\To\LearnTypetta\node_modules\@graphql-codegen\cli\index.js:995:60
    at async C:\Path\To\LearnTypetta\node_modules\@graphql-codegen\cli\index.js:843:21
```

Note that the [hello world example](https://github.com/twinlogix/typetta-examples/tree/main/hello-world) works fine.

**Comment by Atlinx** [comment]
It looks like typetta requires the `uuid` package, and without it, it causes this error. The "getting started" docs should be updated to mention the need for `uuid` to be installed.

**Comment by minox86** [comment]
Hi Atlix, we'll investigate it as soon as possibile. We recently refactored the project dependencies and maybe this is a bug. The only dependency you should need is @twinlogix/typetta.

**Comment by edobrb** [comment]
Hello Atlinx, thanks for reporting the problem. On version 1.3.6-2 the generation should be working even without the uuid explicit dependency.
